#!/bin/bash

output=$(ddcutil -t getvcp 10 2>/dev/null)

if [ $? -eq 0 ]; then
    trimmed=${output#* * * }
    value=${trimmed%% *}

    cached_value=$(cat /tmp/waybar_ddcutil_value 2>/dev/null)
    if [ "$cached_value" != "$value" ]; then
        echo $value > /tmp/waybar_ddcutil_value
    fi
    if [ -z "$1" ]; then
        echo {\"percentage\": $value}
        exit 0
    fi
    if [ "$1" == "up" ]; then
        ddcutil setvcp 10 $((value + 10))
    elif [ "$1" == "down" ]; then
        ddcutil setvcp 10 $((value - 10))
    fi
else
    echo {\"percentage\": $(cat /tmp/waybar_ddcutil_value 2>/dev/null || echo 0)}
fi
