#!/bin/bash
# Print the argumment to a file into the tmp folder
if [[ ! -d "./tmp" ]]; then
	mkdir -p "./tmp"
fi

if [[ ! -f "./tmp/layer.txt" ]]; then
	touch ./tmp/layer.txt
fi

echo "$1" > ./tmp/layer.txt
