require("plugins.comment-config")
require("plugins.gitsigns-config")
require("plugins.lualine-config")
require("plugins.nvim-autopairs-config")
require("plugins.nvimtree-config")
require("plugins.nvim-treesitter-config")
require("plugins.nvim-ts-autotag-config")
require("plugins.telescope-config")
require("plugins.noice-nvim-config")
require("plugins.lsp.lsp-config")
require("plugins.session-manager-config")
require("plugins.obsidian-nvim-config")
require("plugins.dashboard-nvim-config")
-- require('plugins.null-ls-config')
require("plugins.snippets")
require("plugins.mason-config")
require("plugins.lsp.linting-config")
-- require('plugins.vim-markdown-config')
require("plugins.ai.chatgpt-nvim-config")
