require('plugins.comment-config')
require('plugins.gitsigns-config')
require('plugins.lualine-config')
require('plugins.nvim-autopairs-config')
require('plugins.nvimtree-config')
require('plugins.nvim-treesitter-config')
require('plugins.nvim-ts-autotag-config')
require('plugins.telescope-config')
require('plugins.lsp.lsp-config')

